export const COUNTRIES = [
  "Afghanistan", "Albania", "Algeria", "Andorra", "Angola", "Antigua and Barbuda", "Argentina", "Armenia", "Australia", "Austria", "Azerbaijan",
  "Bahamas", "Bahrain", "Bangladesh", "Barbados", "Belarus", "Belgium", "Belize", "Benin", "Bhutan", "Bolivia", "Bosnia and Herzegovina", "Botswana", "Brazil", "Brunei", "Bulgaria", "Burkina Faso", "Burundi",
  "Cabo Verde", "Cambodia", "Cameroon", "Canada", "Central African Republic", "Chad", "Chile", "China", "Colombia", "Comoros", "Congo (Congo-Brazzaville)", "Costa Rica", "Croatia", "Cuba", "Cyprus", "Czechia",
  "Democratic Republic of the Congo", "Denmark", "Djibouti", "Dominica", "Dominican Republic",
  "Ecuador", "Egypt", "El Salvador", "Equatorial Guinea", "Eritrea", "Estonia", "Eswatini", "Ethiopia",
  "Fiji", "Finland", "France",
  "Gabon", "Gambia", "Georgia", "Germany", "Ghana", "Greece", "Grenada", "Guatemala", "Guinea", "Guinea-Bissau", "Guyana",
  "Haiti", "Holy See", "Honduras", "Hungary",
  "Iceland", "India", "Indonesia", "Iran", "Iraq", "Ireland", "Israel", "Italy", "Ivory Coast",
  "Jamaica", "Japan", "Jordan",
  "Kazakhstan", "Kenya", "Kiribati", "Kuwait", "Kyrgyzstan",
  "Laos", "Latvia", "Lebanon", "Lesotho", "Liberia", "Libya", "Liechtenstein", "Lithuania", "Luxembourg",
  "Madagascar", "Malawi", "Malaysia", "Maldives", "Mali", "Malta", "Marshall Islands", "Mauritania", "Mauritius", "Mexico", "Micronesia", "Moldova", "Monaco", "Mongolia", "Montenegro", "Morocco", "Mozambique", "Myanmar",
  "Namibia", "Nauru", "Nepal", "Netherlands", "New Zealand", "Nicaragua", "Niger", "Nigeria", "North Korea", "North Macedonia", "Norway",
  "Oman",
  "Pakistan", "Palau", "Palestine", "Panama", "Papua New Guinea", "Paraguay", "Peru", "Philippines", "Poland", "Portugal",
  "Qatar",
  "Romania", "Russia", "Rwanda",
  "Saint Kitts and Nevis", "Saint Lucia", "Saint Vincent and the Grenadines", "Samoa", "San Marino", "Sao Tome and Principe", "Saudi Arabia", "Senegal", "Serbia", "Seychelles", "Sierra Leone", "Singapore", "Slovakia", "Slovenia", "Solomon Islands", "Somalia", "South Africa", "South Korea", "South Sudan", "Spain", "Sri Lanka", "Sudan", "Suriname", "Sweden", "Switzerland", "Syria",
  "Taiwan", "Tajikistan", "Tanzania", "Thailand", "Timor-Leste", "Togo", "Tonga", "Trinidad and Tobago", "Tunisia", "Turkey", "Turkmenistan", "Tuvalu",
  "Uganda", "Ukraine", "United Arab Emirates", "United Kingdom", "United States of America", "Uruguay", "Uzbekistan",
  "Vanuatu", "Venezuela", "Vietnam",
  "Yemen",
  "Zambia", "Zimbabwe"
];

export const COMMITTEES = [
  "United Nations General Assembly (UNGA)",
  "Disarmament and International Security Committee (DISEC)",
  "Economic and Financial Committee (ECOFIN)",
  "Social, Humanitarian and Cultural Committee (SOCHUM)",
  "Special Political and Decolonization Committee (SPECPOL)",
  "Administrative and Budgetary Committee (GA5)",
  "Legal Committee (GA6)",
  "United Nations Security Council (UNSC)",
  "Economic and Social Council (ECOSOC)",
  "United Nations Human Rights Council (UNHRC)",
  "United Nations Children's Fund (UNICEF)",
  "World Health Organization (WHO)",
  "United Nations Educational, Scientific and Cultural Organization (UNESCO)",
  "United Nations Environment Programme (UNEP)",
  "International Court of Justice (ICJ)",
  "United Nations High Commissioner for Refugees (UNHCR)",
  "United Nations Development Programme (UNDP)",
  "United Nations Office on Drugs and Crime (UNODC)",
  "International Atomic Energy Agency (IAEA)",
  "Commission on the Status of Women (CSW)",
  "United Nations Women (UN Women)",
  "World Food Programme (WFP)",
  "International Labour Organization (ILO)",
  "Food and Agriculture Organization (FAO)",
  "World Trade Organization (WTO)",
  "International Monetary Fund (IMF)",
  "The World Bank",
  "Group of 20 (G20)",
  "Group of 7 (G7)",
  "African Union (AU)",
  "European Union (EU)",
  "North Atlantic Treaty Organization (NATO)",
  "League of Arab States (Arab League)",
  "Association of Southeast Asian Nations (ASEAN)",
  "Organisation of Islamic Cooperation (OIC)",
  "Shanghai Cooperation Organisation (SCO)",
  "Organization of American States (OAS)",
  "Historical Security Council (HSC)",
  "Crisis Committee",
  "Continuous Crisis Committee (CCC)",
  "Joint Crisis Committee (JCC)",
  "Press Corps",
  "International Press Forum",
  "United Nations Commission on Crime Prevention and Criminal Justice (CCPCJ)",
  "United Nations Permanent Forum on Indigenous Issues (UNPFII)",
  "United Nations Commission on Science and Technology for Development (CSTD)"
];
